disabled_rules:
    - cyclomatic_complexity
    - function_body_length
    - legacy_hashing
    - multiple_closures_with_trailing_closure
    - opening_brace
  
opt_in_rules:
    - anonymous_argument_in_multiline_closure
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters_brackets
    - private_subject
    - switch_case_on_newline
    - test_case_accessibility
    - vertical_whitespace_closing_braces
    - weak_delegate
  
multiline_arguments:
    only_enforce_after_first_closure_on_first_line: true

line_length: 100

identifier_name:
    min_length: 2
    max_length: 50
    allowed_symbols: [_]

type_name:
    max_length: 50

